=== hding7788-spec/149/PDM/ootbActions/actionmodels.dtd
<!-- XML definition file for actionmodels (groups of actions) -->
<!-- Within the comments, syntax of the form "objecttype.name" refers to the value of the "name" attribute within the "objecttype" element -->

<!ELEMENT actionmodels ( internal | include | model )* >
<!ATTLIST actionmodels resourceBundle CDATA #IMPLIED> <!-- specifies the class name of the resource bundle to use for the properties of the actionmodel that are to be localized -->

<!ELEMENT model ( action*, submodel*, internal* ) >
<!ATTLIST model name CDATA #REQUIRED >      <!-- commonly referenced in classes of the form StandardNmDocumentService -->
<!ATTLIST model menufor CDATA #IMPLIED >      <!-- ? -->
<!ATTLIST model replace ( true ) #IMPLIED > <!-- determines if this action list will be replaced by see-actions list when user has set that preference -->
<!ATTLIST model defaultActionName CDATA #IMPLIED >
<!ATTLIST model defaultActionType CDATA #IMPLIED >
<!ATTLIST model resourceBundle CDATA #IMPLIED> <!-- specifies the class name of the resource bundle to use for the properties of the actionmodel that are to be localized -->

<!ELEMENT action (internal*, command?, supportedTypes?, nonSupportedTypes?, label?, title?, icon?, tooltip?, moreurlinfo?, ribbonInfo?) >
<!ATTLIST action name NMTOKEN #REQUIRED >   <!-- these name and type attributes must match an objecttype.name and action.name in an actions.xml -->
<!ATTLIST action type NMTOKEN #REQUIRED >   <!-- see above -->
<!ATTLIST action shortcut ( false | true ) #IMPLIED >    <!-- specifies whether an action is to be displayed in table/tree toolbar's shortcut icons area.The action has to be most commonly used action. --> 
<!ELEMENT command EMPTY >
<!ATTLIST command class CDATA #IMPLIED >                 <!-- used only when renderType="PDM" or windowType is <default> or normal; in later case class and method are handler of post -->
<!ATTLIST command method CDATA #IMPLIED >                <!-- used only when renderType="PDM" or windowType is <default> or normal; in later case class and method are handler of post -->
<!ATTLIST command url CDATA #IMPLIED >                   <!-- used to override the generated URL, can be just a query string if the value starts with a ? -->
<!ATTLIST command onClick CDATA #IMPLIED >               <!-- used to specify an additional onclick function to call, can be useful for confirming with user whether to execute special action or not-->
<!ATTLIST command multiselect NMTOKEN #IMPLIED >         <!-- ? -->
<!ATTLIST command windowType ( applet | new | no_content | normal | page | popup | wizard_step ) #IMPLIED >

<!ELEMENT supportedTypes ( type* )>
<!ATTLIST supportedTypes value CDATA #REQUIRED >

<!ELEMENT nonSupportedTypes ( type* )>
<!ATTLIST nonSupportedTypes value CDATA #REQUIRED >


<!ELEMENT submodel (internal)* >
<!ATTLIST submodel name NMTOKEN #REQUIRED >

<!ELEMENT include EMPTY>
<!ATTLIST href name CDATA #REQUIRED >

<!ELEMENT label (#PCDATA)>                     <!--Specifies the label while defining the action  -->
<!ELEMENT title (#PCDATA)>		       <!--Specifies the title while defining the action  -->
<!ELEMENT icon (#PCDATA)>		       <!--Specifies the icon while defining the action  -->
<!ELEMENT tooltip (#PCDATA)>		       <!--Specifies the tooltip while defining the action  -->
<!ELEMENT moreurlinfo (#PCDATA)>               <!--Specifies the moreurlinfo while defining the action  -->

<!ELEMENT ribbonInfo EMPTY>               <!--Specifies the ribbonInfo while defining the action  -->
<!ATTLIST ribbonInfo groupName CDATA "" >
<!ATTLIST ribbonInfo buttonType ( none | button | menu | text_menu | submenu | toggle | custommenu | split | check | subcheck | menuitem | submenuitem | group | simplecustommenu | simpletoggle | endmenu | endsubmenu ) "button" >
<!ATTLIST ribbonInfo buttonScale ( small | medium | large ) "small" >
<!ATTLIST ribbonInfo columnCount CDATA "-1" >

<!ELEMENT includeFilter EMPTY>
<!ATTLIST includeFilter name CDATA #REQUIRED >

<!ELEMENT excludeFilter EMPTY>
<!ATTLIST excludeFilter name CDATA #REQUIRED >

=== hding7788-spec/149/PDM/ootbActions/ManagedCollection-actionmodels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM "http://www.ptc.com/Windchill/config/actions/actionmodels.dtd">

<actionmodels resourceBundle="com.ptc.core.managedcollection.ManagedCollectionActionsRB">
   <model name="more managedcollection actions" menufor="wt.facade.persistedcollection.ManagedCollection">
      <description>Managed Collection row level Actions menu</description>
      <action name="view" type="object"/>
      <action name="separator" type="separator"/>
      <action name="edit_managedcollection" type="managedcollection"/>
      <action name="separator" type="separator"/>
      <action name="copy" type="object"/>
      <action name="renameObjectWizard" type="object"/>
      <action name="CONTAINERMOVE"  type="pdmObject"/>
      <action name="delete_object" type="object"/>
      <action name="separator" type="separator"/>
      <submodel name="more managedcollection toolbar actions add"/>
      <action name="wtObjCompare" type="ocmp"/>
      <action name="ManageSecurity" type="accessPermission"/>
      <action name="createSubscription" type="subscription"/>
   </model>

   <model name="more managedcollection toolbar actions add">
      <action name="addToManagedCollection" type="managedcollection"/>
      <action name="addToPackageSingle" type="wpcollection"/>
   </model>

   <model name="third level nav menubar managedcollection">
      <submodel name="general"/>
      <submodel name="relatedItems"/>
      <submodel name="history"/>
      <submodel name="collaboration"/> 
   </model>

   <model name="managedCollectionDefaultTabSet" >
      <!-- Managed Collection info page default tabs -->
      <submodel name="managedCollectionDetailsTab"/>
      <action name="mc_content" type="managedcollection"/>
   </model>

   <model name="managedCollectionDetailsTab" resourceBundle="com.ptc.core.managedcollection.ManagedCollectionActionsRB">
      <action name="primaryAttributes"     type="object"/>
      <action name="attributes" type="object"/>
   </model>

   <model name="managed collection content row actions">
      <!-- Row level Actions menu for objects within a Managed Collection -->
      <action name="removeMembers" type="wpcollection"/>
      <action name="addToManagedCollection" type="managedcollection"/>
   </model>
   
   <model name="managedcollection content list table toolbar actions">
      <action name="removeMembers" type="wpcollection" shortcut="true"/>
      <action name="addToManagedCollection" type="managedcollection" shortcut="true"/>
      <action name="refreshManagedCollection" type="managedcollection" shortcut="true"/>
      <action name="explode" type="folder" shortcut="true"/>
      <action name="implode" type="folder" shortcut="true"/>
   </model>

   <model name="tombstoneDetailsTab" resourceBundle="com.ptc.core.managedcollection.ManagedCollectionActionsRB">
       <action name="primaryAttributes" type="object"/>
   </model>

   <model name="tombstoneDefaultTab">
       <submodel name="tombstoneDetailsTab"/>
   </model>

   <model name="tombstoneCustomization">
      <action name="primaryAttributes" type="object"/>
   </model>
   
</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/ConfigurableLinkUI-actionmodels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM 'actionmodels.dtd'>

<actionmodels>
    <model name="Configurable Link Table Toolbar">
        <action shortcut="true" name="configurableLink_add"         	 type="object" /> 		 <!-- Find and add objects -->
        <action shortcut="true" name="configurableLink_newDoc"      	 type="document" /> 	 <!-- Create new document and add link -->
        <action shortcut="true" name="configurableLink_newPart"     	 type="part" /> 		 <!-- Create new part and add link -->
        <action shortcut="true" name="configurableLink_newChangeRequest" type="changeRequest" /> <!-- Create new change request and add link -->
		<action shortcut="true" name="configurableLink_newProblemReport" type="problemReport" /> <!-- Create new problem report and add link -->
		<action shortcut="true" name="configurableLink_newChangeNotice"  type="changeNotice" />  <!-- Create new change notice and add link -->
        <action shortcut="true" name="configurableLink_remove"      	 type="object" /> 		 <!-- Remove selected objects -->
        <action shortcut="true" name="configurableLink_editMulti"   	 type="object" /> 		 <!-- Edit multiple rows -->
        <action 				name="separator" 						 type="separator"/>
        <action 				name="configurableLink_copy"        	 type="object" /> 		 <!-- Copy objects to clipboard -->
        <action 				name="configurableLink_paste"       	 type="object" /> 		 <!-- Paste objects from clipboard -->
        <action 				name="configurableLink_pasteSelect" 	 type="object" /> 		 <!-- Paste-select objects from clipboard -->
    </model>

    <model name="Configurable Link Edit Table Toolbar">
        <action name="editProperties" type="object" shortcut="true" />
    </model>

</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/ChangeDirective-actionModels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM '../../actionmodels.dtd'>
<!-- define the actions on the UI components -->
<actionmodels>

   
   <model name="third_level_nav_changeDirective" defaultActionName="impactedItemAndActions" defaultActionType="changeDirective" >
      <description>Third level nav for change directive with default action impacted item and actions</description>
      <submodel name="general"/>
      <submodel name="relatedDirItems"/>
      <submodel name="history"/>
      <submodel name="collaboration"/>
   </model>

   <model name="third_level_nav_changeAction" defaultActionName="modificationStack" defaultActionType="changeAction" >
      <description>Third level nav for change action with default action modification stack</description>
      <submodel name="general"/>
	  <submodel name="changes"/>
      <submodel name="actioncollaboration"/>
   </model>

    <!-- Change Action Collaboration -->
    <model name="actioncollaboration" resourceBundle="com.ptc.windchill.enterprise.changeDirective.changeDirectiveClientResource">
       <description>Third level nav for collaboration on change action info page</description>
       <action name="discuss"                           type="forum"/>
    </model>

   <model name="changeAction row actions" menufor="wt.change2.ChangeAction">
      <description>Change action row actions</description>
      <action name="view" type="object"/>
      <action name="fulfillChangeActions" type="effectivity"/>
      <action name="undoFulfillChangeActionInfoPage" type="effectivity"/>
      <action name="modifyStatus"         type="changeAction"/>
   </model>

   <model name="changeDirective row actions" menufor="wt.change2.WTChangeDirective">
      <description>Change directive row actions</description>
      <action name="view"                       type="object"/>
      <action name="editChangeDirective"        type="changeDirective"/>
      <action name="separator"                  type="separator"/>
      <action name="renameDirectiveWizard"      type="changeDirective"/>
      <action name="deleteChangeDirective"      type="changeDirective"/>
      <action name="separator"                  type="separator"/>
      <action name="reassignLC"                 type="lifecycle"/> <!-- Reassign Life Cycle -->
      <action name="resetTeam"                  type="team"/>
      <action name="setState"                   type="lifecycle"/>
      <action name="separator"                  type="separator"/>
      <action name="bookmarkIt"                 type="bookmark"/>     <!-- add to notebook -->
      <action name="ManageSecurity"             type="accessPermission"/>
      <action name="securityLabelsSingleObjJCA" type="securityLabels"/>
      <action name="createSubscription"         type="subscription"/>
   </model>

   <model name="changedirective.impactedItems.table.view">
      <description>Toolbar action for configuration item table on the change directive info page</description>
      <action name="removeImpactedItems" type="changeDirective" shortcut="true"/>
      <action name="addImpactedItems_Inline" type="changeDirective" shortcut="true"/>
   </model>

   <model name="changedirective.impactedItems.table.create_edit">
         <description>Toolbar action for configuration item flat table on the change directive wizards</description>
         <action name="remove"           type="object" shortcut="true"/>
         <action name="addImpactedItems_Wizard" type="changeDirective" shortcut="true"/>
   </model>

   <model name="impactingDirectives toolbar actions">
     <description>Toolbar action for change directive table on the configuration item info page</description>
     <action name="removeDirectives"         type="changeDirective" shortcut="true"/>
     <action name="addDirectives"            type="changeDirective" shortcut="true"/>
     <action name="GenerateChangeActions"    type="effectivity" shortcut="true"/>
   </model>

   <model name="impactedItemAndChangeAction.row.actions" >
      <description>Toolbar action for configuration item tree table on the change directive wizards</description>
      <action name="GenerateChangeActions"           type="effectivity"/>
      <action name="fulfillChangeActions"            type="effectivity"/>
      <action name="undoFulfillChangeActionInfoPage" type="effectivity"/>
   </model>

  
 </actionmodels>

=== hding7788-spec/149/PDM/ootbActions/smb-actionmodels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM '../../actionmodels.dtd'>

<!-- define the actions on the UI components -->
<actionmodels>
  <model name="smbWizardButtonsNoApply">
	  <action name="prevButton"       type="object"/>
      <action name="nextButton"       type="object"/>
      <action name="okButton"         type="object"/>
      <action name="cancelButton"     type="object"/>
   </model>
   <model name="userTableActions">
      <action name="addUserButton"    type="smb" shortcut="true"/>
      <action name="deleteUserButton" type="smb" shortcut="true"/>
      <action name="editUserButton"   type="smb" shortcut="true"/>
   </model>
      <model name="cadAttributesTableActions">
      <action name="addAttributeButton"    type="smb" shortcut="true"/>
      <action name="deleteAttributeButton" type="smb" shortcut="true"/>
      <action name="editAttributeButton"   type="smb" shortcut="true"/>
   </model>
</actionmodels>
