=== hding7788-spec/149/PDM/ootbActions/actionmodels.dtd
<!-- XML definition file for actionmodels (groups of actions) -->
<!-- Within the comments, syntax of the form "objecttype.name" refers to the value of the "name" attribute within the "objecttype" element -->

<!ELEMENT actionmodels ( internal | include | model )* >
<!ATTLIST actionmodels resourceBundle CDATA #IMPLIED> <!-- specifies the class name of the resource bundle to use for the properties of the actionmodel that are to be localized -->

<!ELEMENT model ( action*, submodel*, internal* ) >
<!ATTLIST model name CDATA #REQUIRED >      <!-- commonly referenced in classes of the form StandardNmDocumentService -->
<!ATTLIST model menufor CDATA #IMPLIED >      <!-- ? -->
<!ATTLIST model replace ( true ) #IMPLIED > <!-- determines if this action list will be replaced by see-actions list when user has set that preference -->
<!ATTLIST model defaultActionName CDATA #IMPLIED >
<!ATTLIST model defaultActionType CDATA #IMPLIED >
<!ATTLIST model resourceBundle CDATA #IMPLIED> <!-- specifies the class name of the resource bundle to use for the properties of the actionmodel that are to be localized -->

<!ELEMENT action (internal*, command?, supportedTypes?, nonSupportedTypes?, label?, title?, icon?, tooltip?, moreurlinfo?, ribbonInfo?) >
<!ATTLIST action name NMTOKEN #REQUIRED >   <!-- these name and type attributes must match an objecttype.name and action.name in an actions.xml -->
<!ATTLIST action type NMTOKEN #REQUIRED >   <!-- see above -->
<!ATTLIST action shortcut ( false | true ) #IMPLIED >    <!-- specifies whether an action is to be displayed in table/tree toolbar's shortcut icons area.The action has to be most commonly used action. --> 
<!ELEMENT command EMPTY >
<!ATTLIST command class CDATA #IMPLIED >                 <!-- used only when renderType="PDM" or windowType is <default> or normal; in later case class and method are handler of post -->
<!ATTLIST command method CDATA #IMPLIED >                <!-- used only when renderType="PDM" or windowType is <default> or normal; in later case class and method are handler of post -->
<!ATTLIST command url CDATA #IMPLIED >                   <!-- used to override the generated URL, can be just a query string if the value starts with a ? -->
<!ATTLIST command onClick CDATA #IMPLIED >               <!-- used to specify an additional onclick function to call, can be useful for confirming with user whether to execute special action or not-->
<!ATTLIST command multiselect NMTOKEN #IMPLIED >         <!-- ? -->
<!ATTLIST command windowType ( applet | new | no_content | normal | page | popup | wizard_step ) #IMPLIED >

<!ELEMENT supportedTypes ( type* )>
<!ATTLIST supportedTypes value CDATA #REQUIRED >

<!ELEMENT nonSupportedTypes ( type* )>
<!ATTLIST nonSupportedTypes value CDATA #REQUIRED >


<!ELEMENT submodel (internal)* >
<!ATTLIST submodel name NMTOKEN #REQUIRED >

<!ELEMENT include EMPTY>
<!ATTLIST href name CDATA #REQUIRED >

<!ELEMENT label (#PCDATA)>                     <!--Specifies the label while defining the action  -->
<!ELEMENT title (#PCDATA)>		       <!--Specifies the title while defining the action  -->
<!ELEMENT icon (#PCDATA)>		       <!--Specifies the icon while defining the action  -->
<!ELEMENT tooltip (#PCDATA)>		       <!--Specifies the tooltip while defining the action  -->
<!ELEMENT moreurlinfo (#PCDATA)>               <!--Specifies the moreurlinfo while defining the action  -->

<!ELEMENT ribbonInfo EMPTY>               <!--Specifies the ribbonInfo while defining the action  -->
<!ATTLIST ribbonInfo groupName CDATA "" >
<!ATTLIST ribbonInfo buttonType ( none | button | menu | text_menu | submenu | toggle | custommenu | split | check | subcheck | menuitem | submenuitem | group | simplecustommenu | simpletoggle | endmenu | endsubmenu ) "button" >
<!ATTLIST ribbonInfo buttonScale ( small | medium | large ) "small" >
<!ATTLIST ribbonInfo columnCount CDATA "-1" >

<!ELEMENT includeFilter EMPTY>
<!ATTLIST includeFilter name CDATA #REQUIRED >

<!ELEMENT excludeFilter EMPTY>
<!ATTLIST excludeFilter name CDATA #REQUIRED >

=== hding7788-spec/149/PDM/ootbActions/preview-actionModels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE actionmodels SYSTEM "actionmodels.dtd">
<actionmodels>
    <model name="third_level_nav_preview" defaultActionType="preview">
        <description>Third level nav with default action envelope data table</description>
        <submodel name="general"/>
        <submodel name="relatedItems"/>
        <submodel name="history"/>
    </model>

    <model name="previewInfoPageTabSet" resource="ext.casc.preview.previewResource">
        <action name="attributes" type="preview"/>
        <submodel name="previewContentInfo"/>
        <action name="previewObjects" type="preview"/>
        <action name="processHistory" type="workflow"/>
    </model>

    <model name="previewContentInfo" resourceBundle="ext.casc.preview.previewResource">
        <action name="primaryContent" type="object"/>
        <action name="attachments" type="object"/>
        <!-- place holder until defaults are provided -->
    </model>

    <model name="more preview actions" menufor="ext.casc.preview.Preview">
        <action name="updatePreview" type="preview"/>              <!-- Edit -->
        <action name="deletePreview" type="preview"/>         <!-- Delete -->
    </model>

</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/DataMonitor-actionmodels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM 'actionmodels.dtd'>
<actionmodels>

   <!-- Define the Data Monitor Management page -->
   <model name="data monitor actions">  
   </model>
   
   	<model name="data monitor row actions" menufor="com.ptc.windchill.enterprise.datamonitor.DataMonitor">
		<action name="view" type="object"/>
		<action name="editDataMonitor" type="datamonitor" />
		<action name="deleteDataMonitor" type="datamonitor" />
		<action name="executeNowDataMonitor" type="datamonitor" />
	</model>

	<model name="datamonitorinfopageTabSet">
		<submodel name="datamonitorInfo_detailstab"/>
		<submodel name="executedreports_tab"/>
	</model>

	<model name="datamonitorInfo_detailstab" resourceBundle="com.ptc.windchill.enterprise.datamonitor.dataMonitorResource">
		<action name="primaryAttributes" type="object"/>
		<action name="attributes" type="object"/>
	</model>


	<model name="datamonitorinfo_detailstab_nav" >
           <action name="primaryAttributes" type="object"/>
           <action name="attributes" type="object"/>
           <action name="viewExecutedReports" type="savedReportHolder"/>
    </model>
    
    <model name="executedreports_tab" resourceBundle="com.ptc.windchill.enterprise.datamonitor.dataMonitorResource">
		<action name="viewExecutedReports" type="savedReportHolder"/>	
	</model>

</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/rtc-actionmodels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM '../../actionmodels.dtd'>
<actionmodels>
   <model name="third_level_nav_typedIteratedResource">
      <submodel name="typedIteratedResource_general"/>
   </model>   
   
   <model name="typedIteratedResource_general" resourceBundle="com.ptc.windchill.enterprise.traceability.traceabilityResource">
      <description>"General" 3rd level nav menu for TypedIteratedResource</description>
      <action name="primaryAttributes" type="object"/>
   </model>
  
   <!-- tabs for typediteratedresourceInfo Page -->
   <model name="typedIteratedResourceInfoPageTabSet">
      <submodel name="typedIteratedResourceDetails"/>
   </model>
   
   <model name="typedIteratedResourceDetails" resourceBundle="com.ptc.windchill.enterprise.traceability.traceabilityResource">
      <action name="primaryAttributes"     type="object"/>
   </model>
   
   <model name="traceability_toolbar_actions">
      <action name="addTraceability" type="traceable" shortcut="true"/>
      <action name="removeTraceabilityToolbar" type="traceable" shortcut="true"/>
      <action name="clearSuspectFlagToobar" type="traceable" shortcut="true"/>
   </model>
  
   <model name="traceability_RMB_actions">
      <action name="removeTraceabilityRMB" type="traceable"/>
      <action name="markSuspectFlag" type="traceable"/>
      <action name="clearSuspectFlag" type="traceable"/>      
   </model>
   
   <!-- this action model is a dummy toolbar action model that is just for the Mark As Suspect RMB action icon to show up -->
   <model name="toolbarModelNotUsedAnywhere">
      <action name="markSuspectFlag" type="traceable"/>
   </model>
   
</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/msoi-actionmodels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM 'actionmodels.dtd'>
<!-- define the actions on wt.doc.WTDocument -->
<actionmodels>

   <model name="wt.doc.WTDocument.msoi">
      <action name="search" type="object"/>
      <action name="createFromTemplateWizard" type="document"/>
      <action name="create" type="document"/>
      <action name="createMulti" type="document"/>
      <action name="createDocTemplate" type="document"/>
      <action name="separator" type="separator"/>
      <action name="checkout" type="object"/>
      <action name="checkout_and_download" type="wip"/>
      <action name="undocheckout" type="object"/>
      <action name="REVISEITEMS" type="pdmObject"/>
      <action name="edit" type="document"/>
      <action name="checkoutAndEdit" type="document"/>
      <action name="checkin" type="workinprogress"/>
      <action name="replace_content" type="wip"/>
      <action name="renameDocumentWizard" type="document"/>
      <action name="MULTI_OBJ_DELETE" type="pdmObject"/>
      <action name="separator" type="separator"/>
      <action name="download_primary_attachment" type="attachments"/>
      <action name="dti_get_attributes" type="msoi"/>
      <action name="view" type="object"/>
      <action name="setState" type="lifecycle"/>
      <action name="create"   type="promotionRequest"/>
  </model>
  
  <model name="DTI.Explorer.Document.SingleSelect.RMB">
         <action name="view"   type="object"/>    <!-- Info page -->
         <action name="download_primary_attachment"   type="attachments"/>
         <action name="redirect_primary_attachment"   type="attachments"/>
         <action name="checkin"                type="wip"/>       <!-- Check In -->
         <action name="checkout"               type="object"/>    <!-- Check Out -->
         <action name="checkout_and_download"  type="wip"/>       <!-- Check Out and Download -->
         <action name="checkoutAndEdit"        type="document"/>  <!-- Check Out and Edit -->
         <action name="undocheckout"           type="object"/>    <!-- Undo Checkout -->
         <action name="edit"                   type="document"/> <!-- Edit -->
         <action name="REVISEITEMS"            type="pdmObject"/> <!-- Revise -->  
         <action name="renameDocumentWizard"   type="document"/>  <!-- doc specific Rename --> 
         <action name="setState"               type="lifecycle"/> <!-- Set State -->
         <action name="MULTI_OBJ_DELETE"       type="pdmObject"/> <!-- Delete -->
         <action name="reassignLC"             type="lifecycle"/>    <!-- Reassign Life Cycle -->
         <action name="create"                 type="promotionRequest"/> <!-- Promote --> 
         <action name="ManageSecurity"     type="accessPermission"/> <!-- Edit Access Control -->
         <action name="EDITSECURITYLABELS" type="object"/>  <!-- Edit Security Label -->
  </model>

  <model name="DTI.Explorer.Folder.SingleSelect.RMB">
		 <action   name="edit"                 type="folder" />                   <!-- Edit -->
		 <action name="MULTI_OBJ_DELETE" type="pdmObject" />      <!-- multiObject Delete -->
         <action name="ManageSecurity"     type="accessPermission"/> <!-- Edit Access Control -->
         <action name="EDITSECURITYLABELS" type="object"/>  <!-- Edit Security Label -->
  </model>
  
  <model name="DTI.Explorer.MultiSelect.RMB">
         <action name="MULTI_OBJ_DELETE" type="pdmObject" />      <!-- multiObject Delete -->
  </model>
  
  <model name="DTI.Explorer.Link.SingleSelect.RMB">
  	<action name="edit_bk" type="bookmark"/>
  	<action name="delete"       type="bookmark"/> <!-- Delete -->
  </model>
  
  <model name="DTI.Explorer.Document.MultiSelect.RMB">
	     <action name="SETSTATE"                type="pdmObject"/> <!-- Set State -->
	     <action name="multiObjectCheckIn"      type="wip" />      <!-- multiObject CheckIn -->
	     <action name="multiObjectCheckOut"     type="wip"/>       <!-- Check out -->
	     <action name="multiObjectUndoCheckout" type="wip" />      <!-- multiObject UndoCheckout -->
		 <action name="MULTI_OBJ_DELETE" type="pdmObject" />       <!-- multiObject Delete -->
  </model>
  
  <model name="wt.meeting.TraditionalMeeting.msoi">
      <action name="create" type="meeting"/>
      <action name="cancel" type="meeting"/>
  </model>
  <model name="wt.meeting.MeetingCenterMeeting.msoi">
      <action name="create" type="meeting"/>
      <action name="cancel" type="meeting"/>
  </model>
  <model name="third_level_nav_dti" defaultActionName="attributes" defaultActionType="object">
       <action name="attributes"                            type="object"/>
       <action name="primaryContent"                        type="object"/>     
       <action name="attachments"                           type="object"/>
  </model>

  <model name="DTIInfoPageWizardButtons">
            <action name="moreInfoButton"  type="msoi"/>
            <action name="closeButton"  type="object"/>
    </model>

</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/QueryBuilder-actionModels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM '../../actionmodels.dtd'>
<actionmodels>
    <!-- action models for Query Builder wt.query.template.ReportTemplate -->
    <model name="report template actions">
        <action name="createReportTemplate" type="queryBuilder" shortcut="true"/>
        <action name="deleteReportTemplate" type="queryBuilder" shortcut="true" />  		
        <action name="importReportTemplate" type="queryBuilder" shortcut="true"/>
        <action name="exportReportTemplates" type="queryBuilder" shortcut="true"/>
        <action name="uploadReportTemplateFromQML" type="queryBuilder" shortcut="true"/>
        <action name="refreshComponent"  type="object" shortcut="true"/>
        <action name="upgradeDashboard" type="queryBuilder" shortcut="true"/>
        <action name="legacyQueryBuilder" type="queryBuilder" shortcut="true"/>
    </model>    
       
    <model name="report template row actions" menufor="wt.query.template.ReportTemplate">
        <action name="view" type="object"/>
        <action name="viewReportTemplate" type="queryBuilder"/>
        <action name="editReportTemplate" type="queryBuilder" />
        <action name="deleteReportTemplate" type="queryBuilder" />
        <action name="exportReportTemplate" type="queryBuilder" />
        <action name="saveReportTemplateAsQML" type="queryBuilder" />
    </model>
       
    <!-- To follow UI standards, the action service is designed to only show the icons in the actions menu if those 
         icons also appear in some toolbar anywhere in the system. If you need to workaround this for some action 
         that does not belong in any toolbar, create a dummy model with your -->
    <model name="toolbarModelNotUsedAnywhere">
        <action name="viewReportTemplate" type="queryBuilder"/>
        <action name="editReportTemplate" type="queryBuilder"/>
        <action name="saveReportTemplateAsQML" type="queryBuilder"/>
    </model> 
</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/Subscription-actionmodels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM '../../actionmodels.dtd'>

<!-- define the actions on the UI components -->
<actionmodels>
   <model name="subscription table actions" >
      <action name="deleteSubscription"      type="subscription" shortcut="true"/>
      <action name="unsubscribeSubscription" type="subscription" shortcut="true"/>
   </model>
   <model name="object subscription table actions" >
      <action name="deleteSubscription"                type="subscription" shortcut="true"/>
      <action name="unsubscribeSubscription"           type="subscription" shortcut="true"/>
      <action name="separator"                         type="separator" shortcut="true"/>
      <action name="createSubscriptionObjSubscrAddRow" type="subscription" shortcut="true"/>
   </model>
   <model name="subscription row actions">
      <action name="object"                type="view"/>
      <action name="deleteSubscriptionRow" type="subscription"/>
      <action name="unsubscribeRow"        type="subscription"/>
      <action name="editSubscription"      type="subscription"/>
   </model>
   <model name="subscription tln row actions">
      <action name="object"                type="view"/>
      <action name="deleteSubscriptionRow" type="subscription"/>
      <action name="unsubscribeTlnRow"     type="subscription"/>
      <action name="editSubscription"      type="subscription"/>
   </model>
   <model name="subscription info actions">
      <action name="deleteSubscriptionInfo"      type="subscription"/>
      <action name="unsubscribeSubscriptionInfo" type="subscription"/>
      <action name="editSubscription"            type="subscription"/>
   </model>
   
   <!-- customized nav menu bar for subscriptions -->
   <model name="subscription_customized_nav" defaultActionName="attributes" defaultActionType="object">  
      <action name="attributes" type="object"/>
      <action name="primaryAttributes"      type="object"/>
      <action name="subscriptionRecipients" type="subscription"/>
      <action name="subscriptionSubscribedObjects" type="subscription"/>
   </model>

   <model name="SubscriptionInfoPageTabset" resourceBundle="com.ptc.core.subscription.subscriptionResource">
      <submodel name="SubscriptionInfoDefaultDetailsTab"/> 
      <submodel name="SubscriptionInfoRecipientsTab"/>
      <submodel name="SubscriptionInfoSubscribedObjectsTab"/> 
   </model>

   <model name="SubscriptionInfoDefaultDetailsTab" resourceBundle="com.ptc.core.subscription.subscriptionResource">
      <action name="primaryAttributes" type="object"/>
      <action name="attributes" type="object"/> 
   </model>

   <model name="SubscriptionInfoRecipientsTab" resourceBundle="com.ptc.core.subscription.subscriptionResource">
      <action name="subscriptionRecipients" type="subscription"/> 
   </model>

   <model name="SubscriptionInfoSubscribedObjectsTab" resourceBundle="com.ptc.core.subscription.subscriptionResource">
      <action name="subscriptionSubscribedObjects" type="subscription"/> 
   </model>

</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/IXB-actionModels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM '../../actionmodels.dtd'>

<actionmodels>
    <model name="actionList_details_importJob" menufor="com.ptc.windchill.ixb.importer.ImportJob">
        <action name="delete" type="ixb"/>
        <action name="cancel" type="ixb"/>
    </model>
    <model name="3rdLevelNav_importJob">
        <description>Import Job third level navigation actions</description>
        <submodel name="general" />
        <action name="baselineList"  type="ixb"/>
    </model>
    <model name="importJobInfoPageTabSet" >
        <description>Tab Set for Import Job Info Page</description>
        <submodel name="importJobDetailsTab"/>       
    </model>
    <model name="importJobDetailsTab" resourceBundle="com.ptc.windchill.ixb.importer.importerResource" >
        <description>Import Job Details tab actions</description>
        <action name="primaryAttributes" type="object"/>
        <action name="attributes" type="object"/>
        <action name="primaryContent" type="object"/> 
        <action name="attachments" type="object"/>
        <action name="baselineList"  type="ixb"/>
    </model>
    
   <model name="importJobMonitorTable_action_column" resourceBundle="com.ptc.windchill.ixb.importJobMonitor.importJobMonitorResource">
      <action name="delete"             type="ixb"/>
   </model>

    <model name="importJobMonitorTable_toolbar" resourceBundle="com.ptc.windchill.ixb.importJobMonitor.importJobMonitorResource">
      <action name="refreshImportJobTable"                 type="ixb" shortcut="true" />
      <action name="autoRefreshImportJobTable"             type="ixb" shortcut="true"/>
       <action name="separator"                      type="separator"/>
       <action name="deleteSelectedJobs"             type="ixb" shortcut="true"/>
    </model>
   
	<model name="importFromSpreadsheetWizardButtons" resourceBundle="com.ptc.windchill.ixb.importer.importerResource" >
		<action name="prevButton" type="object"/>
		<action name="nextButton" type="ixb"/>
		<action name="importButton" type="ixb" />
		<action name="cancelButton" type="object"/>
	</model>

	<model name="import_xlsx_error_display_table_toolbar_actions" resourceBundle="com.ptc.windchill.ixb.importer.importerResource">
		
		<action name="stopSpreadsheetValidation" type="ixb" shortcut="true"/>
    </model>
   
	 <model name="ExportSpreadsheetWizardButtons">
		<action name="exportSpreadsheetOkButton" type="ixb"/>
		 <action name="cancelButton" type="object"/>
    </model>
    
    <model name="ExportSpreadsheetSetAttributeWizardButtons">
		<action name="exportSpreadsheetSetAttributeOkButton" type="ixb"/>
		<action name="cancelButton" type="object"/>
    </model>
</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/MassUpdate-actionModels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM '../../actionmodels.dtd'>

<actionmodels>

    <model name="massUpdate.roleA.table">
        <action name="collectRoleAObjects" type="massUpdate"/>
    </model>

    <model name="MassUpdateWizardButtons">
       <action name="previewButton" type="massUpdate"/>
       <action name="massUpdateBackButton" type="massUpdate"/>
       <action name="prevButton"    type="object"/>
       <action name="nextButton"    type="object"/>
       <action name="okButton"      type="object"/>
       <action name="cancelButton"  type="object"/>
    </model>
</actionmodels>
