=== hding7788-spec/149/PDM/ootbActions/actionmodels.dtd
<!-- XML definition file for actionmodels (groups of actions) -->
<!-- Within the comments, syntax of the form "objecttype.name" refers to the value of the "name" attribute within the "objecttype" element -->

<!ELEMENT actionmodels ( internal | include | model )* >
<!ATTLIST actionmodels resourceBundle CDATA #IMPLIED> <!-- specifies the class name of the resource bundle to use for the properties of the actionmodel that are to be localized -->

<!ELEMENT model ( action*, submodel*, internal* ) >
<!ATTLIST model name CDATA #REQUIRED >      <!-- commonly referenced in classes of the form StandardNmDocumentService -->
<!ATTLIST model menufor CDATA #IMPLIED >      <!-- ? -->
<!ATTLIST model replace ( true ) #IMPLIED > <!-- determines if this action list will be replaced by see-actions list when user has set that preference -->
<!ATTLIST model defaultActionName CDATA #IMPLIED >
<!ATTLIST model defaultActionType CDATA #IMPLIED >
<!ATTLIST model resourceBundle CDATA #IMPLIED> <!-- specifies the class name of the resource bundle to use for the properties of the actionmodel that are to be localized -->

<!ELEMENT action (internal*, command?, supportedTypes?, nonSupportedTypes?, label?, title?, icon?, tooltip?, moreurlinfo?, ribbonInfo?) >
<!ATTLIST action name NMTOKEN #REQUIRED >   <!-- these name and type attributes must match an objecttype.name and action.name in an actions.xml -->
<!ATTLIST action type NMTOKEN #REQUIRED >   <!-- see above -->
<!ATTLIST action shortcut ( false | true ) #IMPLIED >    <!-- specifies whether an action is to be displayed in table/tree toolbar's shortcut icons area.The action has to be most commonly used action. --> 
<!ELEMENT command EMPTY >
<!ATTLIST command class CDATA #IMPLIED >                 <!-- used only when renderType="PDM" or windowType is <default> or normal; in later case class and method are handler of post -->
<!ATTLIST command method CDATA #IMPLIED >                <!-- used only when renderType="PDM" or windowType is <default> or normal; in later case class and method are handler of post -->
<!ATTLIST command url CDATA #IMPLIED >                   <!-- used to override the generated URL, can be just a query string if the value starts with a ? -->
<!ATTLIST command onClick CDATA #IMPLIED >               <!-- used to specify an additional onclick function to call, can be useful for confirming with user whether to execute special action or not-->
<!ATTLIST command multiselect NMTOKEN #IMPLIED >         <!-- ? -->
<!ATTLIST command windowType ( applet | new | no_content | normal | page | popup | wizard_step ) #IMPLIED >

<!ELEMENT supportedTypes ( type* )>
<!ATTLIST supportedTypes value CDATA #REQUIRED >

<!ELEMENT nonSupportedTypes ( type* )>
<!ATTLIST nonSupportedTypes value CDATA #REQUIRED >


<!ELEMENT submodel (internal)* >
<!ATTLIST submodel name NMTOKEN #REQUIRED >

<!ELEMENT include EMPTY>
<!ATTLIST href name CDATA #REQUIRED >

<!ELEMENT label (#PCDATA)>                     <!--Specifies the label while defining the action  -->
<!ELEMENT title (#PCDATA)>		       <!--Specifies the title while defining the action  -->
<!ELEMENT icon (#PCDATA)>		       <!--Specifies the icon while defining the action  -->
<!ELEMENT tooltip (#PCDATA)>		       <!--Specifies the tooltip while defining the action  -->
<!ELEMENT moreurlinfo (#PCDATA)>               <!--Specifies the moreurlinfo while defining the action  -->

<!ELEMENT ribbonInfo EMPTY>               <!--Specifies the ribbonInfo while defining the action  -->
<!ATTLIST ribbonInfo groupName CDATA "" >
<!ATTLIST ribbonInfo buttonType ( none | button | menu | text_menu | submenu | toggle | custommenu | split | check | subcheck | menuitem | submenuitem | group | simplecustommenu | simpletoggle | endmenu | endsubmenu ) "button" >
<!ATTLIST ribbonInfo buttonScale ( small | medium | large ) "small" >
<!ATTLIST ribbonInfo columnCount CDATA "-1" >

<!ELEMENT includeFilter EMPTY>
<!ATTLIST includeFilter name CDATA #REQUIRED >

<!ELEMENT excludeFilter EMPTY>
<!ATTLIST excludeFilter name CDATA #REQUIRED >

=== hding7788-spec/149/PDM/ootbActions/ContextBuilderCustom-actionModels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM '../../actionmodels.dtd'>

  <!-- define the actions on the UI components -->
<actionmodels>

  <model name="carRelatedCADDocsTreeContextMenuProE">
  	<action name="editIncludeExcludeRulesRMC1GWT" type="contextbuildercustom" />
    <action name="editIncludeExcludeRulesRMC2GWT" type="contextbuildercustom" />
    <action name="viewInfoGWT" type="car" />
    <action name="separator" type="separator" />
    <action name="expandAllLevelsGWT" type="cat" />
    <action name="collapseAllLevelsGWT" type="cat" />
    <action name="separator" type="separator" />
    <action name="setProximityFilter"     type="car"/>
    <action name="setProximityRule" type="car" />
    <action name="separator" type="separator" />
    <submodel name="includeRepGroupProE" />
    <action name="separator" type="separator" />
    <action name="clearRep" type="car" />
    <action name="separator" type="separator" />
    <action name="excludeRep" type="car" />
  </model>
  
  <model name="carRelatedCADDocsTreeContextMenuCatiaV5">
	<action name="editIncludeExcludeRulesRMC1GWT" type="contextbuildercustom" />
    <action name="editIncludeExcludeRulesRMC2GWT" type="contextbuildercustom" />
    <action name="viewInfoGWT" type="car" />
    <action name="separator" type="separator" />
    <action name="expandAllLevelsGWT" type="cat" />
    <action name="collapseAllLevelsGWT" type="cat" />
    <action name="separator" type="separator" />
    <action name="setProximityFilter"     type="car"/>
    <action name="setProximityRule" type="car" />
    <action name="separator" type="separator" />
    <submodel name="includeRepGroupCatiaV5" />
    <action name="separator" type="separator" />
    <action name="clearRep" type="car" />
    <action name="separator" type="separator" />
    <action name="excludeRep" type="car" />
  </model>
  
  <model name="carRelatedCADDocsTreeContextMenuWindchill">
	<action name="editIncludeExcludeRulesRMC1GWT" type="contextbuildercustom" />
	<action name="editIncludeExcludeRulesRMC2GWT" type="contextbuildercustom" />
	<action name="viewInfoGWT" type="car" />
	<action name="separator" type="separator" />
	<action name="expandAllLevelsGWT" type="cat" />
	<action name="collapseAllLevelsGWT" type="cat" />
	<action name="separator" type="separator" />
	<action name="setProximityFilter"     type="car"/>
	<action name="setProximityRule" type="car" />
	<action name="separator" type="separator" />
	<submodel name="includeRepGroupWindchill" />
	<action name="separator" type="separator" />
	<action name="clearRep" type="car" />
	<action name="separator" type="separator" />
	<action name="excludeRep" type="car" />
  </model>

  <model name="carRulesToolBar">
    <action name="deleteRuleGWT" type="car" />
    <action name="editIncludeExcludeRulesGWT" type="contextbuildercustom" />
    <action name="editIncludeExcludeRules2GWT" type="contextbuildercustom" />
  </model>

</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/CustomerSupport-actionModels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM '../../actionmodels.dtd'>
	<!-- define the actions on the UI components -->
<actionmodels resourceBundle="com.ptc.customersupport.customerSupportResource">

  <!-- Site Information definitions -->
	<!-- Tree examples related entries -->
	<model name="CustomerSupport_toolbar_actions">
	    <action name="gatherSaveWizard" type="object" shortcut="true"/>
		<action name="explode" type="folder" shortcut="true"/>
		<action name="implode" type="folder" shortcut="true"/>
		<action name="createCategoryWizard" type="object" shortcut="true"/>
		<action name="deleteCategoryAction" type="object" shortcut="true"/>
	</model>
	
	<model name="CustomerSupport_Column_Actions">
		<action name="gatherSaveWizardActionMenu" type="object"/>
		<action name="editCategoryWizard" type="object"/>
		<action name="deleteCategoryActionMenu" type="object"/>
	</model>
	
    <model name="createCategoryWizardButtons">
    	<action name="prevButton" type="object"/>
		<action name="nextButton" type="object"/>
        <action name="okButton" type="object"/>
        <action name="cancelButton" type="object"/>
    </model>
	
</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/RelContext-actionmodels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM 'actionmodels.dtd'>
<!-- define the actions for RelContext Module -->
<actionmodels>
   <!-- define the action models for Related Context -->
   <!-- com.ptc.core.relcontext.server.ContextLink -->
   <model name="contextlink_table">
      <action name="list_delete" type="contextlink" shortcut="true"/>
      <action name="create_context_wizard" type="contextlink" shortcut="true"/>
      <action name="send_relcontext_notification_wizard" type="contextlink" shortcut="true"/>     
   </model>

   <model name="contextlink" menufor="com.ptc.core.relcontext.server.ContextLink">
      <action name="update_context_wizard" type="contextlink"/>
      <action name="delete" type="contextlink"/>
   </model>

   <!-- define the action models for Network page -->
   <!-- com.ptc.core.relcontext.server.NetworkLink -->
   <model name="network_list_table">
      <action name="list_copy"                         type="object" shortcut="true"/>
      <action name="network_paste"                type="network" shortcut="true"/>
      <action name="network_list_delete"                  type="network"/>
      <action name="networkSearch"               type="search"/>
      <action name="separator"                    type="separator"/>
      <action name="explode"         type="folder"/>
      <action name="implode"         type="folder"/>
      <action name="separator"                    type="separator"/>
      <action name="create_folder_network"        type="folder" shortcut="true"/>
      <action name="add_link_network"             type="bookmark" shortcut="true"/>
      <action name="networklink_create_wizard"    type="networklink" shortcut="true"/>
      <action name="relatedItemSearch"               type="search"/>
	  <action name="separator" type="separator" />
   	  <submodel name="nm_exportlisttofile_submenu" />

   </model>

   <model name="network folder toolbar row actions">
      <action name="edit_folder_network"                       type="folder"/>
      <action name="delete"                     type="object"/>
      <action name="separator"                    type="separator"/>
      <action name="add_link_network"                     type="bookmark"/>
      <action name="create_folder_network"                type="folder"/>
      <action name="networklink_create_wizard"    type="networklink"/>
   </model>

   <model name="networklink toolbar row actions" menufor="com.ptc.core.relcontext.server.NetworkLink">
      <action name="networklink_update_wizard"	type="networklink"/>
      <action name="delete"                     type="networklink"/>
      <action name="separator"                    type="separator"/>
      <action name="add_link_network"                     type="bookmark"/>
      <action name="create_folder_network"                type="folder"/>
      <action name="networklink_create_wizard"    type="networklink"/>
   </model>

    <!-- project list table actions in Program Network Page -->
   <model name="network project list">
   		<action name="addToFavorites" type="object" shortcut="true"/>
   		<action name="removeFromFavorites" type="object" shortcut="true"/>
   </model>
</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/csm-actionmodels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM 'actionmodels.dtd'>
<!-- define the actions on the UI components -->
<actionmodels>
	<model name="csm_clfnodetree_actions_toolbar"> <!--This action model is used for csm node tree -->
		<action name="expandAllClfNode" type="csm" /> <!-- Expand All -->
		<action name="collapseAllClfNode" type="csm" /> <!-- Collapse All -->
		<action name="insertClfNode" type="csm" shortcut="true" /> <!-- Insert -->
		<action name="deleteClfNode" type="csm" shortcut="true" /> <!-- Delete -->
		<action name="copyClfNode" type="csm" shortcut="true" /> <!-- Copy -->
		<action name="pasteClfNode" type="csm" shortcut="true" /> <!-- Paste -->
		<submodel name="csmExport"/> <!-- Export submenu actions -->
		<action name="csmImport" type="csm" /> <!-- Import -->
	</model>

	<model name="csm_clfnodetree_row_toolbar"> <!--This action model is used for csm row level action -->
		<action name="expandClfNode" type="csm" /> <!-- Expand All -->
		<action name="collapseClfNode" type="csm" /> <!-- Collapse All -->
		<action name="insertClfNodeRow" type="csm" shortcut="true" /> <!-- Insert -->
		<action name="deleteClfNodeRow" type="csm" shortcut="true" /> <!-- Delete -->
		<action name="copyClfNodeRow" type="csm" /> <!-- Copy -->
		<action name="pasteClfNodeRow" type="csm" shortcut="true" /> <!-- Paste -->
	</model>


	<!-- The top tab set in the node info page. -->
	<model name="csmnode_infoPage_tabSet">
		<action name="clfNodeProperties" type="csm" />
		<action name="typeLayouts" type="lwcType" />
		<action name="node.attribute.multiedit" type="csm" />
		<action name="clfNodeAutonamingProperties" type="csm" />
	</model>

	<!-- the reason "toolbar" is in the name is so that icons will appear for
		all the actions -->
	<model name="csmnode actions toolbar">
		<action name="insertClfNodeDetails" type="csm" shortcut="true" />
		<action name="editCSMNode" type="csm" />
		<action name="infoPageDeleteClfNode" type="csm" /> <!-- Delete -->
	</model>

	<!-- This action model is used for attribute table level actions -->
	<model name="csmattribute table actions toolbar">
		<action name="addAttribute" type="csm" shortcut="true" />
		<action name="deleteAttribute" type="csm" shortcut="true" />
		<action name="collectAttributes" type="csm" shortcut="true" />
		<action name="moveAttributeToParent" type="csm" shortcut="true" />
	</model>

	<model name="clf admin toolbar">
		<description>Toolbar actions for the classification administrators
			table</description>
		<action name="addToClfAdmin" type="csm" shortcut="true" />
		<action name="removeFromClfAdmin" type="csm" shortcut="true" />
	</model>

	<model name="clf_admin_row_toolbar">
		<description>Row actions for the classification administrators table</description>
		<action name="removeRowFromClfAdmin" type="csm" />
	</model>


	<!-- The top tab set in the attribute info page. -->
	<model name="csmattribute_infoPage_tabSet">
		<action name="attributeProperties" type="csm" />
		<action name="attributeValues" type="lwcType" />
		<!-- action name="attributeLegalTypes" type="lwcType"/ -->
        <action name="attributeVisibility" type="csm" />
		<action name="attributeConstraints" type="lwcType" />
	</model>

	<model name="csmattribute row level actions">
		<action name="attributeInfo" type="csm" />
		<action name="deleteAttribute" type="csm" />
		<action name="moveAttributeToParentRow" type="csm" />
	</model>

	<model name="csmExport" resourceBundle="com.ptc.windchill.csm.client.csmClientResource">
		<description>Actions in Export submenu</description>
		<action name="exportToCSV" type="csm" /> <!-- Export To CSV -->
		<action name="exportToXML" type="csm" /> <!-- Export To XML -->
	</model>

</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/Rule-actionmodels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM '../../actionmodels.dtd'>

<!-- define the actions on the UI components -->
<actionmodels>
   <model name="rule toolbar actions">
      <action name="list_delete"            type="object" shortcut="true"/>
      <action name="separator"              type="separator"/> 
      <action name="createRule"   	    type="rule" shortcut="true"/>
      <action name="downloadCompositeRule"  type="rule" shortcut="true"/>
   </model>
   
   <model name="rule actions">
      <action name="editRuleRow"       	    type="rule"/>
      <action name="downloadRuleRow"        type="rule"/>
      <action name="enableRuleRow" 	    type="rule"/>
      <action name="disableRuleRow"         type="rule"/>
      <action name="delete"      	    type="object"/>
   </model>  
</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/auditing-actionmodels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM 'actionmodels.dtd'>
<!-- define the actions on the UI components -->
<actionmodels>
   <model name="report query row actions" resourceBundle="com.ptc.core.auditing.auditingResource">
      <action name="auditReportGenerator" type="auditing"/>
      <action name="object" type="view"/>
      <action name="deleteReportQuery" type="auditing"/>
      <action name="exportReportQuery" type="auditing"/>
   </model>
   
   <model name="report query schedule row actions" resourceBundle="com.ptc.core.auditing.auditingResource">
      <action name="auditReportGenerator" type="auditing"/>
      <action name="object" type="view"/>
      <action name="delete" type="object"/>
      <action name="exportReportQuery" type="auditing"/>
      <action name="scheduleReportQuery" type="auditing"/>
      <action name="cancelReportQuerySchedule" type="auditing"/>
   </model>

   <model name="report query info actions" resourceBundle="com.ptc.core.auditing.auditingResource">
      <action name="auditReportGenerator" type="auditing"/>
      <action name="deleteReportQueryInfo" type="auditing"/>
      <action name="exportReportQuery" type="auditing"/>
   </model>
   
   <model name="report query schedule info actions" resourceBundle="com.ptc.core.auditing.auditingResource">
      <action name="auditReportGenerator" type="auditing"/>
      <action name="deleteReportQueryInfo" type="auditing"/>
      <action name="exportReportQuery" type="auditing"/>
      <action name="scheduleReportQuery" type="auditing"/>
      <action name="cancelReportQuerySchedule" type="auditing"/>
   </model>
   
   <!-- customized nav menu bar for report query -->
   <model name="report_query_customized_nav" defaultActionName="attributes" defaultActionType="object">
      <action name="attributes" type="object"/>  
      <action name="primaryAttributes"  type="object"/>
   </model>

   <model name="ReportQueryInfoDefaultDetailsTab" resourceBundle="com.ptc.core.auditing.auditingResource">
      <action name="primaryAttributes" type="object"/>
      <action name="attributes" type="object"/>
   </model>
 
   <model name="ReportQueryInfoPageTabset" resourceBundle="com.ptc.core.auditing.auditingResource">
      <submodel name="ReportQueryInfoDefaultDetailsTab"/> 
   </model>

   <model name="report query toolbar actions">
      <action name="list_delete" type="object" shortcut="true"/>
   </model>
   
   <model name="license count change history toolbar actions">
      <action name="separator" type="separator"/>
      <action name="editLicenseCount" type="auditing"/>
   </model>
   
   <model name="license usage toolbar actions">
      <action name="exportLicenseUsageReport" type="auditing" shortcut="true"/>
      <action name="editReportDistribution" type="auditing" shortcut="true"/>
   </model>

   <model name="ProI license usage toolbar actions">
      <action name="exportLicenseUsageReport" type="auditing" shortcut="true"/>
      <action name="editLicenseCount" type="auditing" shortcut="true"/>
      <action name="editReportDistribution" type="auditing" shortcut="true"/>
      <action name="licenseCountChangeHistory" type="auditing" shortcut="true"/>
   </model>
   
   <model name="license usage row actions">
      <action name="viewLicenseUsageDrillDown" type="auditing"/>
   </model>

   <model name="license usage info page navigation">
      <action name="usage_reporting" type="auditing"/>
      <action name="view_print_license_reporting" type="auditing"/>
      <action name="importable_zip_licenses_reporting" type="auditing"/>     
      <action name="windchill_MES_integration_licenses_reporting" type="auditing"/>
   </model>
   
   <model name="ProI license usage info page navigation">
      <action name="license_usage_reporting" type="auditing"/>
   </model>
   
   <model name="view print license group row actions">
      <action name="view_print_member_size" type="auditing" shortcut="true"/>
      <submodel name="folderbrowser_toolbar_exportlisttofile_submenu"/>
   </model>
   
   <model name="organization usage toolbar actions">
      <action name="exportLicenseUsageReport" type="auditing" shortcut="true"/>
   </model>
   
   <model name="organization usage row actions">
      <action name="viewOrganizationUsageDrillDown" type="auditing"/>
   </model>
   
   <model name="purge manager toolbar actions">
      <action name="purgeAuditLog" type="auditing" shortcut="true"/>
   </model>
   
   <model name="importable zip license group row actions">
      <action name="importable_zip_licenses_group_size" type="auditing" shortcut="true"/>
      <submodel name="folderbrowser_toolbar_exportlisttofile_submenu"/>
   </model>   
</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/PartInstanceCompare-actionmodels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE actionmodels SYSTEM 'actionmodels.dtd'>

<actionmodels>
   <model name="picTreeToolBarLeft">
	  <action name="resetDualStructureCompare" type="dsb"/>
      <action name="separator" type="separator" />
      <action name="prevDifference" type="dsb"/>
      <action name="nextDifference" type="dsb"/>
      <action name="separator" type="separator" />
      <action name="displayOnlyDifferences" type="dsb"/>
	  <action name="collapseAllLevelsDSB" type="dsb"/>
      <action name="separator" type="separator" />
	  <action name="dsbExportActionGWT" type="dsb" />
	  <action name="dsbExportHtmlGWT" type="dsb" />
	  <action name="dsbExportCsvGWT" type="dsb" />
	  <action name="dsbExportPdfGWT" type="dsb" />
	  <action name="dsbExportTextGWT" type="dsb" />
	  <action name="dsbExportXlsGWT" type="dsb" />
	  <action name="dsbExportXlsxGWT" type="dsb" />
      <action name="ciFilterPropertiesGWT" type="cisb"/>
      <action name="picEditFilterGWT" type="partInstanceCompare"/>
    </model>

	<model name="picTreeToolBarRight">
      <action name="ciFilterPropertiesGWT" type="cisb"/>
      <action name="picEditFilterGWT" type="partInstanceCompare"/>
    </model>

	<model name="picTreeContextMenu">
      <action name="viewInfo" type="dsb"/>
      <action name="copytowindchill" type="dsb"/>
      <action name="expandAllLevelsDSB" type="dsb" />
      <action name="collapseAllLevelsDSB" type="dsb"/>
    </model>
</actionmodels>

=== hding7788-spec/149/PDM/ootbActions/BusinessRulesClient-actionModels.xml
<?xml version="1.0"?>
<!DOCTYPE actionmodels SYSTEM '../../actionmodels.dtd'>
<!-- define the actions on the UI components -->
<actionmodels
	resourceBundle="com.ptc.windchill.enterprise.businessRules.businessRulesClientActionsRB">

	<model name="BusinessRulesResultOk">
		<action name="okButton" type="businessRules" />
	</model>

	<model name="businessRules_results_table">
		<description>Toolbar actions for the results table on the View
			Conflicts link from the workflow task</description>
		<submodel name="exportlisttofile_submenu"/>
	</model>
	
	<model name="businessRules_ruleSets_table">
		<description>Toolbar actions for the rule set table.</description>
        <action name="explode" type="folder" shortcut="true"/>
        <action name="implode" type="folder" shortcut="true"/>		
		<submodel name="exportlisttofile_submenu"/>
	</model>	

</actionmodels>
